- id: '1645440345429'
  alias: motion4
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.motion1_occupancy
    attribute: occupancy
    to: 'true'
  condition: []
  action:
  - type: turn_on
    device_id: 792743b254af7f6173436972f023b74c
    entity_id: switch.rozet1
    domain: switch
  mode: single
