- platform: systemmonitor
  resources:
  - type: processor_use
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: last_boot
  - type: disk_free
    arg: /
    
- platform: filesize
  file_paths:
     - /config/home-assistant_v2.db

- platform: version
  name: current_ha
  scan_interval: 1800

  
- platform: template
  sensors:
    version:
      friendly_name: 'Последняя версия - '
      value_template: '{{ states.binary_sensor.updater.attributes["newest_version"] }}'




